name: build-local-runner
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]   # ‚Üê usa tu runner hector-local
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Dotnet info
        run: dotnet --info
        shell: pwsh

      - name: Restore
        run: dotnet restore ./PruebaTecnicaIIS.csproj
        shell: pwsh

      - name: Build
        run: dotnet build ./PruebaTecnicaIIS.csproj -c Release --no-restore
        shell: pwsh

      - name: Publish
        run: dotnet publish ./PruebaTecnicaIIS.csproj -c Release -o ./publish --no-build
        shell: pwsh
